<?php

namespace App\Policies;

use App\Models\Analytics;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class AnalyticsPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any analytics data.
     * Only Admins can view analytics.
     */
    public function viewAny(User $user)
    {
        return $user->role === 'Admin';
    }

    /**
     * Determine whether the user can view specific analytics data.
     * Only Admins can view analytics.
     */
    public function view(User $user, Analytics $analytics)
    {
        return $user->role === 'Admin';
    }

    /**
     * Determine whether the user can create analytics data.
     * Typically, analytics data is generated by the system, not users.
     */
    public function create(User $user)
    {
        // Deny by default
        return false;
    }

    /**
     * Determine whether the user can update analytics data.
     * Typically, analytics data is not updated manually.
     */
    public function update(User $user, Analytics $analytics)
    {
        // Deny by default
        return false;
    }

    /**
     * Determine whether the user can delete analytics data.
     * Typically, analytics data is not deleted manually.
     */
    public function delete(User $user, Analytics $analytics)
    {
        // Deny by default
        return false;
    }
}
